import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms & Conditions | General Contracting & Engineering Abu Dhabi',
  description: 'Review the terms and conditions of ArrowHead International General Contracting LLC. Governed by the laws of Abu Dhabi, United Arab Emirates.',
  keywords: ['ArrowHead Terms of Service', 'contracting terms Abu Dhabi', 'construction agreement UAE', 'Prestige Towers general contracting'],
  alternates: {
    canonical: 'https://arrowheadigc.com/terms-conditions',
  },
};

export default function TermsConditionsPage() {
  const lastUpdated = 'June 3, 2026';

  return (
    <div id="terms-conditions-container" className="bg-app-bg text-app-fg min-h-screen transition-colors duration-200">
      {/* 1. HERO HEADER */}
      <section className="bg-app-secondary py-20 relative overflow-hidden border-b border-app-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <span className="text-brand-teal text-xs font-bold uppercase tracking-widest font-mono">Legal &amp; Compliance</span>
          <h1 className="text-4xl sm:text-5xl font-heading font-extrabold text-app-fg mt-4 tracking-tight leading-tight">
            Terms &amp; Conditions
          </h1>
          <p className="mt-4 text-xs font-mono text-brand-gold font-semibold uppercase">
            Last Updated: {lastUpdated}
          </p>
        </div>
      </section>

      {/* 2. TERMS CONTENT */}
      <section className="py-24">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-app-card border border-app-border rounded-2xl p-8 sm:p-12 shadow-sm space-y-10 offset-border-frame">
            
            {/* Agreement */}
            <div className="space-y-4">
              <h2 className="text-xl font-heading font-extrabold border-b border-app-border/60 pb-3 text-app-fg">
                1. Acceptance of Terms
              </h2>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                These Terms &amp; Conditions govern the use of this website, online estimators, RFQ tools, and the commercial relationship with <strong className="font-semibold text-app-fg">ArrowHead International General Contracting LLC</strong> (hereinafter referred to as &quot;ArrowHead&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;), licensed under Abu Dhabi Department of Economic Development DED License <strong className="font-semibold text-app-fg">CN-4998977</strong>, with head offices on 5th Floor, Prestige Towers, Mussaffah, Abu Dhabi, United Arab Emirates.
              </p>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                By accessing this website, submitting an RFQ, requesting a construction estimate, or communicating with us, you agree to be bound by these Terms &amp; Conditions, and all applicable federal laws of the United Arab Emirates and local decrees of the Emirate of Abu Dhabi. If you do not accept these terms, you must discontinue the use of this site immediately.
              </p>
            </div>

            {/* Estimators & RFQ Policy */}
            <div className="space-y-4">
              <h2 className="text-xl font-heading font-extrabold border-b border-app-border/60 pb-3 text-app-fg">
                2. RFQs, Online Estimations, and Budget Calculations
              </h2>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                Our website provides online calculators, budget estimators, and RFQ forms to assist prospective clients in evaluating initial costs for HDPE pipeline installation, utility infrastructure, turnkey villa construction, civil extensions, and mechanical, electrical, and plumbing (MEP) works. 
              </p>
              <div className="bg-brand-gold/10 border border-brand-gold/20 rounded-lg p-5 text-brand-gold text-xs sm:text-sm font-medium leading-relaxed my-4">
                <strong>WARNING:</strong> All budget figures, schedules, material selections, and estimates generated by our online tools are preliminary approximations provided for general reference and informational purposes only. They do not constitute an official binding tender, price quote, or contractual offer.
              </div>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                A legally binding agreement for construction, procurement, or maintenance will only be established upon the execution of a formal, written contract physically signed and stamped by the authorized corporate officers of ArrowHead, referencing approved engineering drawings, detailed bills of quantities (BOQ), and specific FIDIC or standard UAE contracting terms.
              </p>
            </div>

            {/* Permitting and Approvals */}
            <div className="space-y-4">
              <h2 className="text-xl font-heading font-extrabold border-b border-app-border/60 pb-3 text-app-fg">
                3. Scope of Works and Municipal Permitting
              </h2>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                All physical works executed by ArrowHead are subject to municipal zoning, utility connections, and structural permits issued by government entities in the Emirate of Abu Dhabi:
              </p>
              <ul className="list-disc pl-5 text-app-muted text-xs sm:text-sm space-y-2 font-light">
                <li><strong className="font-semibold text-app-fg">Client Obligations</strong>: The client is responsible for providing valid plot titles, land maps, design briefs, soil survey clearances, and corporate/individual identification documents required to process permit submissions.</li>
                <li><strong className="font-semibold text-app-fg">TAMM Portal NOCs</strong>: We coordinate TAMM Municipal portal submittals and NOC acquisitions. Any delays caused by municipal authorities, regulatory updates, environmental assessments (EAD), or incomplete client document logs are outside our control and will adjust project schedules accordingly.</li>
                <li><strong className="font-semibold text-app-fg">Utility Inspections</strong>: Pipeline testing, gravity trunk hookups, and electrical board connections are subject to field testing and inspection checks by Abu Dhabi Sewerage Services Company (ADSSC) and Abu Dhabi Distribution Company (ADDC) inspectors. Construction milestones are dependent on obtaining these official inspection stamps.</li>
              </ul>
            </div>

            {/* Intellectual Property */}
            <div className="space-y-4">
              <h2 className="text-xl font-heading font-extrabold border-b border-app-border/60 pb-3 text-app-fg">
                4. Intellectual Property Rights
              </h2>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                Unless otherwise indicated, all website content, source code, visual renders, 3D showcases (including interactive concepts, maps, estimators), architectural drawings, mockups, brand assets, logos, and technical guides are the exclusive intellectual property of ArrowHead and are protected by UAE Federal Law No. 38 of 2021 on Copyrights and Neighboring Rights and UAE Trademark laws. Users are granted a limited license only to view the content for personal or corporate project planning.
              </p>
            </div>

            {/* Liability Limits */}
            <div className="space-y-4">
              <h2 className="text-xl font-heading font-extrabold border-b border-app-border/60 pb-3 text-app-fg">
                5. Limitation of Liability and Force Majeure
              </h2>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                ArrowHead, its directors, and employees shall not be liable for any indirect, incidental, or consequential damages (including loss of business revenue, site delays, material supply fluctuations, or structural modifications) arising from your use of this website or reliance on online budget calculators.
              </p>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                Regarding physical civil works, ArrowHead operates under UAE Decennial Liability provisions (Articles 880 to 883 of the UAE Civil Code), guaranteeing structural envelope integrity for ten (10) years post-occupancy certificate. We are not liable for delays, halts, or damage resulting from Force Majeure events including extreme weather (sandstorms, floods), material supply chain blockades, environmental agency holds, or changes in UAE building regulations.
              </p>
            </div>

            {/* Governing Law */}
            <div className="space-y-4">
              <h2 className="text-xl font-heading font-extrabold border-b border-app-border/60 pb-3 text-app-fg">
                6. Governing Law and Dispute Resolution
              </h2>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                These Terms &amp; Conditions, and any disputes, tenders, or contracts associated with ArrowHead, shall be governed by, construed, and enforced in accordance with the laws of the Emirate of Abu Dhabi and the Federal Laws of the United Arab Emirates. Any legal action, lawsuit, or arbitration arising from these terms or our services shall be filed and resolved exclusively before the competent Courts of Abu Dhabi, United Arab Emirates.
              </p>
            </div>

            {/* Contact */}
            <div className="space-y-4 pt-6 border-t border-app-border/60">
              <h2 className="text-lg font-heading font-extrabold text-brand-teal">
                7. Legal Contact
              </h2>
              <p className="text-app-muted text-xs sm:text-sm leading-relaxed font-light">
                For questions regarding these Terms &amp; Conditions or formal contract frameworks (including FIDIC agreements or Annual Maintenance SLA models), contact our legal department:
              </p>
              <div className="bg-app-secondary border border-app-border rounded-lg p-5 mt-3 text-xs sm:text-sm space-y-1">
                <p className="font-semibold text-app-fg">ArrowHead International General Contracting LLC</p>
                <p className="text-app-muted">Legal Affairs &amp; Tenders Department</p>
                <p className="text-app-muted">5th Floor, Prestige Towers, Mussaffah, Abu Dhabi, United Arab Emirates</p>
                <p className="text-brand-teal font-mono">Email: legal@arrowheadigc.com</p>
                <p className="text-app-muted">Phone: +971 2 554 5230</p>
              </div>
            </div>

          </div>
        </div>
      </section>
    </div>
  );
}
